language: node_js
branches:
    only:
        - master
node_js:
    - "12"
    - "10"
    - "8"
matrix:
    allow_failures:
        - node_js: "12"
addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-4.8
        - g++-4.8
        - libsnappy-dev
        - realpath
install:
    - export CC="gcc-4.8"
    - export CXX="g++-4.8"
    - mkdir deps
    - git clone https://github.com/openvenues/libpostal
    - cd libpostal
    - ./bootstrap.sh
    - ./configure --datadir=$(pwd)/data --prefix=$(realpath $(pwd)/../deps) --bindir=$(realpath $(pwd)/../deps)
    - make install
    - cd ..
    - export CXXFLAGS=-I$(pwd)/deps/include
    - export LDFLAGS=-L$(pwd)/deps/lib
    - npm install
script:
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/deps/lib
    - npm test
